server.port=8082
spring.main.banner-mode=off

# PostgreSQL Database Configuration
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/simulation_db}
spring.datasource.username=${DB_USERNAME:postgres}
# If your database password is different, please modify the password property below
spring.datasource.password=${DB_PASSWORD:12345678}
spring.datasource.driver-class-name=${DB_DRIVER:org.postgresql.Driver}

# GeoServer Configuration
geoserver.url=${GEOSERVER_URL:http://localhost:8080/geoserver/vishal/wms}
geoserver.layers=${GEOSERVER_LAYERS:vishal:NE2_HR_LC_SR_W_DR}

# JPA / Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=WARN
