server.port=8082
spring.main.banner-mode=off

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/simulation_db
spring.datasource.username=postgres
# If your database password is different, please modify the password property below
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=WARN
